### ISSUE TITLE
Getting an error on start when io_device is set to a file.

### ISSUE THREAD

**Issue by nateless** [ivx/ink#67]
Hey,

`Interactive Elixir (1.10.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :gen_event handler Ink installed in Logger terminating
** (exit) an exception was raised:
    ** (ErlangError) Erlang error: :terminated
        (stdlib 3.13) :io.put_chars(#PID<0.120.0>, :unicode, ["{\"application\":\"phoenix\",\"domain\":[\"elixir\"],\"erlang_pid\":\"#PID<0.567.0>\",\"file\":\"lib/phoenix/endpoint/cowboy2_adapter.ex\",\"function\":\"start_link/3\",\"gl\":\"#PID<0.550.0>\",\"hostname\":\"nateless\",\"level\":30,\"line\":95,\"mfa\":\"{Phoenix.Endpoint.Cowboy2Adapter, :start_link, 3}\",\"module\":\"Elixir.Phoenix.Endpoint.Cowboy2Adapter\",\"msg\":\"Running AuthWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4000 (http)\",\"name\":\"Auth\",\"pid\":15227,\"time\":\"2020-07-29T18:34:34.667Z\",\"v\":0}", 10])
        (ink 1.2.0) lib/ink.ex:100: Ink.handle_event/2
        (stdlib 3.13) gen_event.erl:620: :gen_event.server_update/4
        (stdlib 3.13) gen_event.erl:602: :gen_event.server_notify/4
        (stdlib 3.13) gen_event.erl:343: :gen_event.handle_msg/6
        (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3`

Config:
`config :logger, Ink, name: "Auth", io_device: File.open!("logs/log.json", [:append])`

**Comment by mmainz** [comment]
I tried your config, but it works fine for me, I couldn't reproduce that error at all. Please make a repository where I can reproduce the issue. Until then, I'm closing this.

**Comment by nateless** [comment]
I've uploaded a test repo: https://github.com/nateless/testlog

here's how I've created it:
`mix phx.new  --no-webpack --no-ecto --no-html --no-dashboard testlog`


```
➜  testlog iex -S mix phx.server
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.10.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :gen_event handler Ink installed in Logger terminating
** (exit) an exception was raised:
    ** (ErlangError) Erlang error: :terminated
        (stdlib 3.13) :io.put_chars(#PID<0.120.0>, :unicode, ["{\"application\":\"phoenix\",\"domain\":[\"elixir\"],\"erlang_pid\":\"#PID<0.278.0>\",\"file\":\"lib/phoenix/endpoint/cowboy2_adapter.ex\",\"function\":\"start_link/3\",\"gl\":\"#PID<0.266.0>\",\"hostname\":\"nateless\",\"level\":30,\"line\":95,\"mfa\":\"{Phoenix.Endpoint.Cowboy2Adapter, :start_link, 3}\",\"module\":\"Elixir.Phoenix.Endpoint.Cowboy2Adapter\",\"msg\":\"Running TestlogWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4000 (http)\",\"name\":\"testlog\",\"pid\":25367,\"time\":\"2020-07-30T14:51:24.790Z\",\"v\":0}", 10])
        (ink 1.2.0) lib/ink.ex:100: Ink.handle_event/2
        (stdlib 3.13) gen_event.erl:620: :gen_event.server_update/4
        (stdlib 3.13) gen_event.erl:602: :gen_event.server_notify/4
        (stdlib 3.13) gen_event.erl:343: :gen_event.handle_msg/6
        (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
```

Error in this line: `:io.put_chars(#PID<0.120.0>, :unicode, []`. There's no `:io.put_chars/3`

**Comment by mmainz** [comment]
Alright, I think I understand the problem now. The process for the file is created when the config file is evaluated, so during build time probably. But later when we try to log to it, the process is not alive anymore, because that PID does not exist anymore. I don't have a workaround right now, but I'll look into a possible solution.
